import{getStorage,load,save,validateSwatch,reorder}from'./state.js';import{renderList,renderStrip,renderCount}from'./ui.js';
const $=id=>document.getElementById(id);
const form=/** @type {HTMLFormElement} */($('swatch-form')),color=/** @type {HTMLInputElement} */($('color')),label=/** @type {HTMLInputElement} */($('label')),error=$('form-error'),list=$('swatch-list'),strip=$('palette-strip'),count=$('count'),notice=$('notice'),dialog=/** @type {HTMLDialogElement} */($('delete-dialog')),deleteCopy=$('delete-copy'),add=/** @type {HTMLButtonElement} */($('add-button'));
const storage=getStorage(),loaded=load(storage);let swatches=loaded.swatches,pendingId=null,lastTrigger=null;
function announce(message,kind='info'){notice.textContent=message;notice.dataset.kind=kind;notice.hidden=false}
function render(){renderList(list,swatches);renderStrip(strip,swatches);renderCount(count,swatches.length);add.disabled=swatches.length>=8;add.textContent=swatches.length>=8?'Palette complete':' + Add to palette'}
function persist(){const result=save(storage,swatches);if(!result.ok)announce(/** @type {{message:string}} */(result).message,'error')}
function setError(message=''){error.textContent=message;error.hidden=!message}
form.addEventListener('submit',event=>{event.preventDefault();const result=validateSwatch(label.value,color.value,swatches.length);if(!result.ok){setError(/** @type {{error:string}} */(result).error);label.focus();return}setError();swatches=[...swatches,/** @type {{value:import('./types').Swatch}} */(result).value];persist();render();form.reset();color.value='#273247';label.focus()});
list.addEventListener('click',event=>{if(!(event.target instanceof Element))return;const button=/** @type {HTMLButtonElement|null} */(event.target.closest('button[data-action]')),row=/** @type {HTMLElement|null} */(event.target.closest('[data-id]'));if(!button||!row)return;const index=swatches.findIndex(s=>s.id===row.dataset.id);if(index<0){announce('That piece is no longer available. Please try again.','error');render();return}if(button.dataset.action==='delete'){pendingId=row.dataset.id;lastTrigger=button;deleteCopy.textContent=`Remove “${swatches[index].label}” from this palette? This cannot be undone.`;dialog.showModal();return}swatches=reorder(swatches,index,button.dataset.action==='up'?-1:1);persist();render()});
dialog.addEventListener('close',()=>{if(dialog.returnValue==='confirm'&&pendingId){swatches=swatches.filter(s=>s.id!==pendingId);persist();render();announce('Swatch removed.')}pendingId=null;lastTrigger?.focus()});
render();if(loaded.message)announce(loaded.message,'error');requestAnimationFrame(()=>$('startup').classList.add('is-hidden'));
