/** @typedef {import('./types').Swatch} Swatch */
const text=(value)=>{const n=document.createElement('span');n.textContent=value;return n};
/** @param {string} hex @returns {{ink:string,shadow:string}} */
const stripContrast=hex=>{const [r,g,b]=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4),l=.2126*r+.7152*g+.0722*b;return l>.179?{ink:'#000',shadow:'none'}:{ink:'#fff',shadow:'0 1px 3px #0008'}};
/** @param {HTMLElement} target @param {Swatch[]} swatches */
export function renderList(target,swatches){target.replaceChildren();if(!swatches.length){const empty=document.createElement('div');empty.className='empty-state';empty.append(Object.assign(document.createElement('strong'),{textContent:'Nothing here yet.'}),text('Start with a color you reach for without thinking.'));target.append(empty);return}swatches.forEach((swatch,index)=>{const row=document.createElement('article');row.className='swatch';row.dataset.id=swatch.id;const color=document.createElement('div');color.className='swatch-color';color.style.background=swatch.hex;color.setAttribute('aria-label',swatch.hex);const info=document.createElement('div');info.className='swatch-info';const name=document.createElement('h3');name.className='swatch-name';name.textContent=swatch.label;const hex=document.createElement('p');hex.className='hex';hex.textContent=swatch.hex;info.append(name,hex);const actions=document.createElement('div');actions.className='swatch-actions';const controls=/** @type {[string,string,boolean][]} */([['up','Move up',index===0],['down','Move down',index===swatches.length-1],['delete','Remove',false]]);controls.forEach(([action,label,disabled])=>{const button=document.createElement('button');button.className=`icon-button ${action==='delete'?'delete':''}`;button.type='button';button.dataset.action=action;button.disabled=disabled;button.textContent=label;actions.append(button)});row.append(color,info,actions);target.append(row)})}
/** @param {HTMLElement} target @param {Swatch[]} swatches */
export function renderStrip(target,swatches){target.replaceChildren();if(!swatches.length){const empty=document.createElement('p');empty.className='strip-empty';empty.textContent='Your colors will collect here.';target.append(empty);return}swatches.forEach(s=>{const item=document.createElement('div'),contrast=stripContrast(s.hex);item.className='strip-item';item.style.background=s.hex;item.style.setProperty('--strip-ink',contrast.ink);item.style.setProperty('--strip-shadow',contrast.shadow);item.title=`${s.label} (${s.hex})`;item.append(text(s.label));target.append(item)})}
/** @param {HTMLElement} target @param {number} count */
export function renderCount(target,count){target.textContent=`${count} of 8 piece${count===1?'':'s'}`}
